version: "3"

name: digital-stores

services:
  auth_service:
    container_name: Auth
    build: ./apps/Auth
    depends_on:
      - auth_service_db

  auth_service_db:
    container_name: AuthDB
    image: postgres:alpine3.16
    environment:
      POSTGRES_USER: ${PG_USER_AUTH}
      POSTGRES_PASSWORD: ${PG_PASSWORD_AUTH}
      POSTGRES_DB: ${PG_DB_AUTH}
    volumes:
      - ./apps/Auth/postgres_data:/var/lib/postgresql/data
    ports:
      - ${PG_PORT_AUTH}:${PG_PORT_AUTH}