version: "3"

name: digital-stores
services:
  auth_service_db:
    container_name: AuthDB
    image: postgres:alpine3.16
    environment:
      POSTGRES_USER: ${PG_USER_AUTH}
      POSTGRES_PASSWORD: ${PG_PASSWORD_AUTH}
      POSTGRES_DB: ${PG_DB_AUTH}
    volumes:
      - ./apps/Auth/postgres_data:/var/lib/postgresql/data
    command: -p ${PG_PORT_AUTH}
    ports:
      - ${PG_PORT_AUTH}:${PG_PORT_AUTH}

  

  category_service_db:
    container_name: CategoryDB
    image: postgres:alpine3.16
    environment:
      POSTGRES_USER: ${PG_USER_CATEGORY}
      POSTGRES_PASSWORD: ${PG_PASSWORD_CATEGORY}
      POSTGRES_DB: ${PG_DB_CATEGORY}
    volumes:
      - ./apps/Category/postgres_data:/var/lib/postgresql/data
    ports:
      - ${PG_PORT_CATEGORY}:${PG_PORT_CATEGORY}
    command: -p ${PG_PORT_CATEGORY}
  

  product_service_db:
    container_name: productDB
    image: postgres:alpine3.16
    environment:
      - POSTGRES_USER: ${PG_USER_PRODUCT} 
      - POSTGRES_PASSWORD: ${PG_PASSWORD_PRODUCT}
      - POSTGRES_DB: ${PG_DB_PRODUCT}
    volumes:
      - ./apps/Product/postgres_data:/var/lib/postgresql/data
    ports:
      - ${PG_PORT_PRODUCT}:${PG_PORT_PRODUCT}
    command: -p ${PG_PORT_PRODUCT}
