"""change type column of hashed_password in the table User

Revision ID: 8b575a725758
Revises: b09f72877d5f
Create Date: 2024-03-26 12:46:29.846324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b575a725758'
down_revision: Union[str, None] = 'b09f72877d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.TEXT(),
               type_=sa.LargeBinary(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.LargeBinary(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
