"""Added CASCADE delete for UserTokenDB table

Revision ID: b50b67a56160
Revises: 8e8123e1a631
Create Date: 2024-04-05 13:30:52.223278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50b67a56160'
down_revision: Union[str, None] = '8e8123e1a631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_constraint('user_token_user_id_fkey', 'user_token', type_='foreignkey')
    op.create_foreign_key(None, 'user_token', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_token', type_='foreignkey')
    op.create_foreign_key('user_token_user_id_fkey', 'user_token', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
